const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = require('./webpack.config.base.js')({
    devtool: 'cheap-module-eval-source-map',
    entry: {
        app: [
            // necessary for hot reloading with IE:
            'eventsource-polyfill',
            // listen to code updates emitted by hot middleware:
            'webpack-hot-middleware/client',
            // your code:
            "./src/index.js"
        ]
    },
    output: {
        publicPath: '/dist/'
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
            hash: true
        })
    ],
    babelQueryPresets: ['react-hmre'],
    scssLoader: 'style-loader?sourceMap!css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!postcss-loader!sass-loader?sourceMap'
});
